config/routes.rb
Rails.application.routes.draw do
  post '/d/new_and_associate' => 'diseases#new_and_associate_patient', as: :new_and_associate_patient, format: :js
  resources :diseases, path: "d", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_disease_code, on: :collection
    get ':patient_id/associate' => 'diseases#associate_patient', as: :associate_patient
    delete ':patient_id/delete' => 'diseases#delete_associate_patient', as: :delete_associate_patient
  end
  resources :consultations
  resources :exams
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, path: "u", path_names: { edit: "e", new: "novo" }
  resources :appointments, path: "consulta", path_names: { edit: "e", new: "novo" }
  resources :patients, path: "p", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_patient_all, on: :collection
  end

  get '/agenda' => 'protocol#protocol', as: :protocol #, format: false
  get '/pesquisar' => 'protocol#search', as: :search #, format: false
  get '/historico/*id' => 'protocol#historic', as: :historic #, format: false

  # config/routes.rb
  get "/pages/*id" => 'pages#show', as: :page, format: false

  # if routing the root path, update for your controller
  root to: 'pages#show', id: 'about'

  delete "/file/:id" => 'application#delete_file', as: :delete_file

  #root to: 'visitors#index'

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :set_disease, only: [:show, :edit, :update, :destroy]
  autocomplete :disease, :code, :display_value => :funky_method, additional_data: [:name, :description, :icd], order: "diseases.name ASC"

  # GET /diseases
  # GET /diseases.json
  def index
    if params[:patient_id]
      @patient = Patient.find(params[:patient_id])
      @diseases = @patient.diseases
    else
      @patient = nil
      @diseases = Disease.all
    end
    respond_to :html, :json, :js
  end

  # GET /diseases/1
  # GET /diseases/1.json
  def show
  end

  # GET /diseases/new
  def new
    @disease = Disease.new
  end

  # GET /diseases/1/edit
  def edit
    respond_to :html, :js#, layout: false
  end

  # POST /diseases
  # POST /diseases.json
  def create
    @disease = Disease.new(disease_params)

    respond_to do |format|
      if @disease.save
        format.html { redirect_to @disease, notice: 'Disease was successfully created.' }
        format.json { render :show, status: :created, location: @disease }
      else
        format.html { render :new }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_and_associate_patient
    disease_code = params["search_disease"]
    patient_id = params["patient_id"]
    patient = Patient.find_by_id(patient_id)

    @disease = Disease.new(code: disease_code)
    @disease.patients << patient

    respond_to do |format|
      if @disease.save
        format.js { flash.now[:notice] = "Nova Doença/Problema (#{@disease.code}) criada e associada ao paciente #{patient.name} com sucesso."}
      else
        format.js { flash.now[:notice] = @consultation.errors }
      end
    end
  end

  # PATCH/PUT /diseases/1
  # PATCH/PUT /diseases/1.json
  def update
    respond_to do |format|
      if @disease.update(disease_params)
        format.html { redirect_to @disease, notice: 'Descrição da Doença/Problema alterada com sucesso.' }
        format.js { flash.now[:notice] = 'Descrição da Doença/Problema alterada com sucesso.'}
        format.json { render :show, status: :ok, location: @disease }
      else
        format.html { render :edit }
        format.js { render :edit, flash.now[:notice] = @consultation.errors }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diseases/1
  # DELETE /diseases/1.json
  def destroy
    @disease.destroy
    respond_to do |format|
      format.html { redirect_to diseases_url, notice: 'Doença/Problema removida com sucesso.' }
      format.js   { flash.now[:notice] = 'Doença/Problema removida com sucesso.'}
      format.json { head :no_content }
    end
  end

  def associate_patient
    disease_id = params["disease_id"]
    patient_id = params["patient_id"]
    patient = Patient.find_by_id(patient_id)
    disease = Disease.find_by_id(disease_id)

    patient.diseases << disease
    patient.save
    respond_to do |format|
      format.js   { flash.now[:notice] = "#{disease.code} associado ao paciente #{patient.name} com sucesso."}
    end
  end

  def delete_associate_patient
    disease_id = params["disease_id"]
    patient_id = params["patient_id"]
    patient = Patient.find_by_id(patient_id)
    disease = Disease.find_by_id(disease_id)

    #patient.diseases.delete(disease) -- estava apagando todas as doenças repetidas, então agora apaga apenas a última repetida
    last_disease = patient.diseases_patients.where(disease_id: disease_id).last
    patient.diseases_patients.destroy(last_disease)
    patient.save
    respond_to do |format|
      #format.html { redirect_to diseases_url, notice: 'Doença/Problema não está mais relacionado com o paciente' }
      format.json { head :no_content }
      format.js   { flash.now[:notice] = "#{disease.code} desassociado do paciente #{patient.name} com sucesso."}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease
      @disease = Disease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_params
      params.require(:disease).permit(:code, :name, :description, :icd)
    end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/views/diseases/_edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Alterar Doença/Problema</h5>
  <button type="button" class="close" data-dismiss="modal" autofocus="true" tabindex="1" aria-label="Fechar">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= render 'form', disease: @disease %>
</div>
<div class="modal-footer">
<!--  <button type="button" class="btn btn-primary">Salvar</button>-->
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</div>

app/views/diseases/_form.html.erb
<%= form_with(model: disease, remote: true) do |form| %>
  <div class="container col-sm-12">
    <% if disease.errors.any? %>
      <div id="error_explanation">
        <!--      <h2><%#= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>-->
        <ul>
          <% disease.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= form.label :code %>
          <%= form.hidden_field :code, value: "#{disease.try(:code)}", class: "autocomplete-target" %>
          <%= text_field_tag :search_disease, (disease.try(:code) || params[:search_disease]), data: { autocomplete_disease: autocomplete_disease_code_diseases_path, hidden:{target: ".autocomplete-target"} }, class: 'form-control autocomplete-disease' %>
        </div>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <%= form.label :icd %>
          <%= form.text_field :icd, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, size: "20x03", class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="actions col-12">
      <%= form.submit({class: 'btn btn-primary right'}) %>
    </div>
  </div>
<% end %>

app/views/diseases/_index.html.erb
<div class="col-sm-6">
  <div class="form-group">
  <%= form_tag(new_and_associate_patient_path(format: :js), method: :post, remote: true) do %>
    <%= label_tag :code, "Doença/Problema" %>
    <%= hidden_field_tag :patient_id, @patient.id %>
    <%= hidden_field_tag :disease_id, "", class: "autocomplete-target" %>
    <%= text_field_tag :search_disease, "", data: { autocomplete: autocomplete_disease_code_diseases_path, hidden:{target: ".autocomplete-target"} }, class: 'form-control autocomplete-disease' %>
    <%= button_tag "Incluir Nova Doença", type: 'submit', class: 'btn btn-primary btn-new-disease', style:'display:none', data:{patient_id: @patient.id} %>
  <% end %>
  </div>
</div>

<table class="responsive nowrap table table-hover dttb" id="dttb-diseases" data-sort="true" data-source="<%= url_for(patient_id: @patient.id, format: :json)%>">
  <thead>
  <tr>
    <!-- <th data-data="patient">Paciente</th> -->
    <th data-data="code">Doença/Problema</th>
<!--    <th data-data="name">Nome</th>-->
<!--    <th data-data="description">descrição</th>-->
<!--    <th data-data="icd">CID</th>-->
    <th data-data="url" data-orderable="false" data-searchable="false" class="skip-export">Ações</th>
  </tr>
  </thead>

</table>
<br>
<%#= link_to 'Incluir Doença', new_disease_path(patient_id: @patient.try(:id)),  {:remote => true, data:{toggle:  "modal", target: '#modal-patient'}, class:"btn btn-primary"} %>

app/views/diseases/_new.html.erb
<div class="modal-header">
    <h5 class="modal-title">Nova Doença</h5>
    <button type="button" class="close" data-dismiss="modal" autofocus="true" tabindex="1" aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <%= render 'form', disease: @disease, disable_field: false %>
</div>
<div class="modal-footer">
    <!--  <button type="button" class="btn btn-primary">Salvar</button>-->
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</div>

app/views/diseases/associate_patient.js.erb
$("#disease_id").val('');
$("#search_disease").val('');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    dttbDiseases.ajax.reload();
});

app/views/diseases/delete_associate_patient.js.erb
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    dttbDiseases.ajax.reload();
});

app/views/diseases/destroy.js.erb
//$("#modal-patient").modal('toggle');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    dttbDiseases.ajax.reload();
});

app/views/diseases/edit.html.erb
<h1>Editing Disease</h1>

<%= render 'form', disease: @disease %>

<%= link_to 'Show', @disease %> |
<%= link_to 'Back', diseases_path %>

app/views/diseases/edit.js.erb
$("#modal-patient").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-patient").modal().animate({ scrollTop: 0 }, 'slow');

app/views/diseases/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="sectionform">
        <h1>Diseases</h1>

        <table class="responsive nowrap table table-hover" id="dttb-diseases" data-sort="true" data-source="<%= url_for(format: :json)%>">
          <thead>
            <tr>
                      <th data-data="code">Code</th>
                      <th data-data="name">Name</th>
                      <th data-data="description">Description</th>
                      <th data-data="icd">Icd</th>
                      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
            </tr>
          </thead>

        </table>

        <br>

        <%= link_to 'New Disease', new_disease_path %>
      </div>
    </div>
  </div>
</div>

app/views/diseases/new.html.erb
<h1>New Disease</h1>

<%= render 'form', disease: @disease %>

<%= link_to 'Back', diseases_path %>

app/views/diseases/new.js.erb
$("#modal-patient").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-patient").modal().animate({ scrollTop: 0 }, 'slow');

app/views/diseases/new_and_associate_patient.js.erb
$(".btn-new-disease").hide();
$("#disease_id").val('');
$("#search_disease").val('');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    dttbDiseases.ajax.reload();
});

app/views/diseases/update.js.erb
$("#modal-patient").modal('toggle');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    dttbDiseases.ajax.reload();
})