config/routes.rb
Rails.application.routes.draw do
  post '/d/new_and_associate' => 'diseases#new_and_associate_patient', as: :new_and_associate_patient, format: :js
  resources :diseases, path: "d", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_disease_code, on: :collection
    get ':patient_id/associate' => 'diseases#associate_patient', as: :associate_patient
    delete ':patient_id/delete' => 'diseases#delete_associate_patient', as: :delete_associate_patient
  end
  resources :consultations
  resources :exams
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, path: "u", path_names: { edit: "e", new: "novo" }
  resources :appointments, path: "consulta", path_names: { edit: "e", new: "novo" }
  resources :patients, path: "p", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_patient_all, on: :collection
  end

  get '/agenda' => 'protocol#protocol', as: :protocol #, format: false
  get '/pesquisar' => 'protocol#search', as: :search #, format: false
  get '/historico/*id' => 'protocol#historic', as: :historic #, format: false

  # config/routes.rb
  get "/pages/*id" => 'pages#show', as: :page, format: false

  # if routing the root path, update for your controller
  root to: 'pages#show', id: 'about'

  delete "/file/:id" => 'application#delete_file', as: :delete_file

  #root to: 'visitors#index'

end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id                            :bigint           not null, primary key
#  user_id                       :bigint
#  protocol_number               :integer
#  patient_since                 :date
#  name                          :string(255)
#  birth                         :date
#  age                           :integer
#  cpf                           :string(255)
#  gender                        :string(255)
#  etnia                         :string(255)
#  civil_status                  :string(255)
#  occupation                    :string(255)
#  scholarity                    :string(255)
#  zip                           :string(255)
#  district                      :string(255)
#  address                       :string(255)
#  city                          :string(255)
#  uf                            :string(255)
#  telephone                     :string(255)
#  mobile                        :string(255)
#  email                         :string(255)
#  indication_by                 :text(65535)
#  health_plan                   :string(255)
#  plan_validation               :date
#  plan_number                   :string(255)
#  history_current_disease       :text(65535)
#  previous_pathological_history :text(65535)
#  mother_history                :text(65535)
#  father_history                :text(65535)
#  social_history                :text(65535)
#  physiological_history         :text(65535)
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  health_insurance              :string(255)
#

class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :exams, inverse_of: :patient, dependent: :destroy
  has_many :diseases_patients
  has_many :diseases, through: :diseases_patients, dependent: :destroy


  #has_many :users, through: :appointments
  belongs_to :user


  serialize :history_current_disease, Hash
  store_accessor :history_current_disease,
                 :main_complaint, :history_of_disease

  serialize :previous_pathological_history, Hash
  store_accessor :previous_pathological_history,
         :suffered_accidents, :have_allergy, :suffers_asthma,:cardiopathies,
                 :previous_surgeries, :convulsions, :diabetes_mellitus, :dyslipidemia,
                 :childhood, :enteropathies, :gastropathy, :previous_hospitalizations,
                 :history_has, :metabolic_diseases, :nephropathy, :pneumopathy, :osteopathy,
                 :thyroid_disease, :suffered_transfusions, :other_diseases, :use_medications

  serialize :mother_history, Hash
  store_accessor :mother_history,
                 :about_mother, :mother_lives, :mother_cardiac, :mother_diabetes,
                        :mother_congenital_disease, :mother_has, :mother_neoplasms, :mother_obesity, :mother_surgeries
  serialize :father_history, Hash
  store_accessor :father_history,
                 :about_father, :father_lives, :father_cardiac, :father_diabetes,
                 :father_congenital_disease, :father_has, :father_neoplasms, :father_obesity, :father_surgeries
  serialize :social_history, Hash
  store_accessor :social_history,
                 :alcoholism, :smoking, :stop_smoking, :ilicit_drugs, :physical_activity, :aerobic_activity, :other_activity
  serialize :physiological_history, Hash
  store_accessor :physiological_history, :sleep_weel, :has_appetite, :intestinal_function, :renal_function, :menstrual_cycle

  attr_accessor :enable_complete_validation

  validates :name, presence: true
  validate :mobile_or_telephone
  validate :validate_format_of_document_number


  scope :filter, -> (user_id, term, order_field, order_dir) {
    limit(15)
    .where(user_id: user_id)
    .where("name like '%#{term.tr(" ", "%")}%' or protocol_number like '#{term}%' or lpad(protocol_number, 5, 0) like '%#{term}%' or cpf like '#{term}%' or email like '%#{term}%' or birth like '%#{term}%'")
    .order("#{order_field} #{order_dir}")
  }

  GENDER = {
      male: "Masculino",
      female: "Feminino",
      not_informed: "Não Informado"
  }

  CIVIL_STATUS = {
      single: "Solteiro(a)",
      married:  "Casado(a)",
      divorcied: "Divorciado(a)",
      spared: "Separado(a)",
      widow: "Viúvo(a)"
  }

  ETNIA= {
      branco: "Branco",
      negro:  "Negro",
      indigena: "Indígena",
      pardo: "Pardo",
      mulato: "Mulato",
      caboclos: "Caboclo",
      cafuzo: "Cafuzo"
  }

  HEALTH_INSURANCE= {
      cortesia: "Cortesia",
      particular: "Particular",
      amil: "Amil",
      bradesco: "Bradesco",
      cassi: "CASSI",
      embratel_claro: "Embratel-CLARO",
      embratel_pame: "Embratel-PAME",
      embratel_telos: "Embratel-TELOS",
      petrobras_ams: "Petrobras-AMS",
      petrobras_di: "Petrobras-DI",
      sulamerica: "Sulamérica",
      unimed: "Unimed"
  }

  SCHOLARITY = {
      none: "Nenhuma",
      first_degree_incomplete: "1o Grau Incompleto",
      first_degree: "1o Grau",
      second_degree_incomplete: "2o Grau Incompleto",
      second_degree: "2o Grau",
      third_degree_incomplete: "3o Grau Incompleto",
      third_degree: "3o Grau",
      pos_mda: "Pós Graduação/MBA",
      master_degree: "Mestrado",
      doctorate_degree: "Doutorado",
      pos_doctorate: "Pós Doutorado"
  }

  def protocol_and_name
    self.protocol_number.blank? ? self.name : "#{self.protocol_number.to_s.rjust(5, "0")}-#{self.name}"
  end

  def last_appointment
    self.appointments.where(status: :done).order(appointment_date: :asc).try(:last).try(:appointment_date).try(:strftime, "%d/%m/%Y")
  end

  def options
    OpenStruct.new self[:options] || {}
  end

  def mobile_or_telephone
    if (enable_complete_validation && (self.mobile.blank? || self.telephone.blank?))
      return errors.add(:mobile, " não pode ficar em branco")
    else
      return true
    end
  end

  def validate_format_of_document_number(cpf=self.cpf)
    if (enable_complete_validation || !cpf.blank?)
      return errors.add(:cpf, " não é válido") if cpf.blank?
      nulos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000}
      valor = cpf.scan /[0-9]/
      if valor.length == 11
        unless nulos.member?(valor.join)
          valor = valor.collect{|x| x.to_i}
          soma = 10*valor[0]+9*valor[1]+8*valor[2]+7*valor[3]+6*valor[4]+5*valor[5]+4*valor[6]+3*valor[7]+2*valor[8]
          soma = soma - (11 * (soma/11))
          resultado1 = (soma == 0 or soma == 1) ? 0 : 11 - soma
          if resultado1 == valor[9]
            soma = valor[0]*11+valor[1]*10+valor[2]*9+valor[3]*8+valor[4]*7+valor[5]*6+valor[6]*5+valor[7]*4+valor[8]*3+valor[9]*2
            soma = soma - (11 * (soma/11))
            resultado2 = (soma == 0 or soma == 1) ? 0 : 11 - soma
            return true if resultado2 == valor[10] # CPF válido
          end
        end
      end
      return errors.add(:cpf, " não é válido")# CPF inválido
    end
  else
    return true
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  #before_action :admin_only#, :except => [:show]

  #autocomplete :patient, :name, :display_value => :funky_method#, label_method: :name, full_mode: true #, scopes: [:active_users]
  autocomplete :patient, :all, :display_value => :funky_method, additional_data: [:cpf, :mobile, :mobile_work, :health_insurance, :telephone_work, :telephone], full_model: true, order: "patients.name ASC"

  # GET /patients
  # GET /patients.json
  def index
    respond_to :html, :json, :js
    _search_value = params["search"]["value"]
    _field_index = params["order"]["0"]["column"]
    _field_name = params["columns"][_field_index]["data"]
    _order_dir = params["order"]["0"]["dir"]
    if current_user.admin?
      @patients = Patient.filter(current_user.id, _search_value, _field_name, _order_dir)
    else
      @patients = Patient.filter(current_user.parent, _search_value, _field_name, _order_dir)
    end
    @patients.all
    # faz a paginação

  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    if current_user.admin?
      _user_id = current_user.id
    else
      _user_id = current_user.parent
    end
    last_protocol_number = Patient.where(user_id: _user_id).maximum(:protocol_number) || 0
    @patient = Patient.new(protocol_number: last_protocol_number + 1)
    respond_to :html, :json, :js
  end

  # GET /patients/1/edit
  def edit
    if @patient.protocol_number.blank?
      if current_user.admin?
        _user_id = current_user.id
      else
        _user_id = current_user.parent
      end
      last_protocol_number = Patient.where(user_id: _user_id).maximum(:protocol_number)  || 0
      @patient.protocol_number = last_protocol_number + 1
    end
    respond_to :html, :js, :json#, layout: false
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    # associa paciente ao médico
    @patient.user_id = (current_user.admin? && current_user.parent.blank?) ? current_user.id : current_user.parent
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Paciente criado com sucesso' }
        format.js { flash.now[:notice] = 'Paciente criado com sucesso!'}
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Paciente atualizado com sucesso!' }
        format.js { flash.now[:notice] = 'Paciente atualizado com sucesso!'}
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to protocol_path, notice: 'Paciente apagado com sucesso!'}
      format.js   { flash.now[:notice] = 'Paciente apagado com sucesso!'}
      format.json { head :no_content }
    end
  end

  private
    # sobrescrevendo métodos do autocomplete para pesquisar em diversas colunas (campos)
    def autocomplete_select_clause(model, value_method, label_method, options)
      table_name = model.table_name
      selects = []
      selects << "#{table_name}.#{model.primary_key}"
      selects << (value_method == 'all') ? "#{table_name}.*" : "#{table_name}.#{value_method}"
      selects << "#{table_name}.#{label_method}" if label_method
      options[:additional_data].each { |datum| selects << "#{table_name}.#{datum}" } if options[:additional_data] && (value_method != 'all')
      selects
    end
    def autocomplete_where_clause(term, model, value_method, options)
      term = term.gsub(/[_%]/) { |x| "\\#{x}" } # escape any _'s or %'s in the search term
      term = "#{term}%"
      term = "%#{term}" if options[:full_search]
      table_name = model.table_name
      lower = options[:case_sensitive] ? '' : 'LOWER'
      #["#{lower}(#{table_name}.#{value_method}) LIKE #{lower}(?)", term] # escape default: \ on postgres, mysql, sqlite

      # marretando a consulta na mão mesmo
      ["#{lower}(patients.name) LIKE #{lower}(?) OR #{lower}(lpad(patients.protocol_number, 5, 0)) LIKE #{lower}(?) OR #{lower}(patients.cpf) LIKE #{lower}(?) OR #{lower}(patients.email) LIKE #{lower}(?) OR #{lower}(patients.mobile) LIKE #{lower}(?)", term.tr(" ", "%"), term.tr(" ", "%"), term.tr(" ", "%"), term.tr(" ", "%"), term.tr(" ", "%")] # escape default: \ on postgres, mysql, sqlite

    end
    def autocomplete_build_json(results, value_method, label_method, options)
      results.collect do |result|
        data = HashWithIndifferentAccess.new(id: result.id,
                                             label: result.send(:protocol_and_name),
                                             value: result.send(:name))
        options[:additional_data].each do |method|
          data[method] = result.send(method)
        end if options[:additional_data]
        data
      end
    end
    ## fim da sobrescrita dos métodos da gem autocomplete

    # Use callbacks to share common setup or constraints between actions.
    def set_patient

      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:protocol_number, :patient_since, :name, :birth, :age, :cpf, :gender, :etnia,
                                      :civil_status, :occupation, :scholarity, :zip, :address, :city, :district, :uf,
                                      :telephone, :mobile, :telephone_work, :mobile_work,
                                      :email, :indication_by, :health_insurance, :health_plan, :plan_validation,
                                      :plan_number, :created_at, :updated_at, :description, :national_identification,
                                      :main_complaint, :history_of_disease,
                                      :suffered_accidents, :have_allergy, :suffers_asthma,:cardiopathies,
                                      :previous_surgeries, :convulsions, :diabetes_mellitus, :dyslipidemia,
                                      :childhood, :enteropathies, :gastropathy, :previous_hospitalizations,
                                      :history_has, :metabolic_diseases, :nephropathy, :pneumopathy, :osteopathy,
                                      :thyroid_disease, :suffered_transfusions, :other_diseases, :use_medications,
                                      :about_mother, :mother_lives, :mother_cardiac, :mother_diabetes,
                                      :mother_congenital_disease, :mother_has, :mother_neoplasms, :mother_obesity,
                                      :mother_surgeries, :about_father, :father_lives, :father_cardiac, :father_diabetes,
                                      :father_congenital_disease, :father_has, :father_neoplasms, :father_obesity,
                                      :father_surgeries, :alcoholism, :smoking, :stop_smoking, :ilicit_drugs, :physical_activity,
                                      :aerobic_activity, :other_activity, :sleep_weel, :has_appetite, :intestinal_function,
                                      :renal_function, :menstrual_cycle)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_consultations.html.erb
<%= form_with(model: patient, remote: true) do |form| %>
  <div class="container col-sm-12">
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
        <div class="col-sm-12"  >
          <div id="div-consultations" data-url="<%= consultations_path(patient_id: patient.id) %>">

          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/patients/_diseases.html.erb
  <div class="container col-sm-12">
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="col-sm-12">
          <div id="div-diseases" class="col-12" data-url="<%= diseases_path(patient_id: patient.id) %>">

          </div>
      </div>
  </div>

app/views/patients/_edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Alterar Paciente</h5>
  <button type="button" class="close" data-dismiss="modal" autofocus="true" tabindex="1" aria-label="Fechar">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= render 'form', patient: @patient %>
</div>
<div class="modal-footer">
<!--  <button type="button" class="btn btn-primary">Salvar</button>-->
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</div>

app/views/patients/_exams.html.erb
<%= form_with(model: patient, remote: true) do |form| %>
  <div class="container col-sm-12">
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <!--      <h2><%#= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>-->
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="col-sm-12">
          <%#= link_to 'Atualizar Modal', exams_path,  {:remote => true, data:{toggle: "modal", target: '#modal-exames'}, class:"btn btn-primary"} %>
          <div id="div-exams" class="col-12" data-url="<%= exams_path(patient_id: patient.id) %>">

          </div>
      </div>
  </div>
<% end %>

app/views/patients/_family_history.html.erb
<%= form_with(model: patient, remote: true) do |form| %>
  <div class="container col-sm-12">
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <!--      <h2><%#= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>-->
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-sm-6">
        <fieldset>
          <legend>História da Mãe</legend>
          <div class="form-group">
            <%= form.label :about_mother %>
            <%= form.text_area :about_mother, size: "25x10", class: 'form-control' %>
          </div>pra
          <div class="form-group">
            <%= form.label :mother_lives %>
            <%= form.text_field :mother_lives, class: 'form-control', title: 'Qual idade?' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_cardiac %>
            <%= form.text_field :mother_cardiac, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_diabetes %>
            <%= form.text_field :mother_diabetes, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_congenital_disease %>
            <%= form.text_field :mother_congenital_disease, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_has %>
            <%= form.text_field :mother_has, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_neoplasms %>
            <%= form.text_field :mother_neoplasms, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_obesity %>
            <%= form.text_field :mother_obesity, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :mother_surgeries %>
            <%= form.text_field :mother_surgeries, class: 'form-control', title: 'Explique' %>
          </div>
        </fieldset>
      </div>
      <div class="col-sm-6">
        <fieldset>
          <legend>História do Pai</legend>
          <div class="form-group">
            <%= form.label :about_father %>
            <%= form.text_area :about_father, size: "25x10", class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :father_lives %>
            <%= form.text_field :father_lives, class: 'form-control', title: 'Qual idade?' %>
          </div>
          <div class="form-group">
            <%= form.label :father_cardiac %>
            <%= form.text_field :father_cardiac, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_diabetes %>
            <%= form.text_field :father_diabetes, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_congenital_disease %>
            <%= form.text_field :father_congenital_disease, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_has %>
            <%= form.text_field :father_has, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_neoplasms %>
            <%= form.text_field :father_neoplasms, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_obesity %>
            <%= form.text_field :father_obesity, class: 'form-control', title: 'Explique' %>
          </div>
          <div class="form-group">
            <%= form.label :father_surgeries %>
            <%= form.text_field :father_surgeries, class: 'form-control', title: 'Explique' %>
          </div>
        </fieldset>
      </div>
      <div class="actions col-12" style="width: 100%; margin-top: 10px">
        <%= form.submit('Atualizar Histórico Familiar',{class: 'btn btn-primary'}) %>
      </div>
    </div>
  </div>
<% end %>

app/views/patients/_social_history.html.erb
<%= form_with(model: patient, remote: true) do |form| %>
  <div class="container col-sm-12">
    <% if patient.errors.any? %>
      <div id="error_explanation">
        <!--      <h2><%#= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>-->
        <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-sm-2">
        &nbsp;
      </div>
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :alcoholism %>
          <%= form.text_field :alcoholism, class: 'form-control', title: "Frequência e quantidade?" %>
        </div>
        <div class="form-group">
          <%= form.label :smoking %>
          <%= form.text_field :smoking, class: 'form-control', title: 'Cigarros/Dia?' %>
        </div>
        <div class="form-group">
          <%= form.label :stop_smoking %>
          <%= form.text_field :stop_smoking, class: 'form-control', title: 'Explique' %>
        </div>
        <div class="form-group">
          <%= form.label :ilicit_drugs %>
          <%= form.text_field :ilicit_drugs, class: 'form-control', title: 'Quais?' %>
        </div>
        <div class="form-group">
          <%= form.label :physical_activity %>
          <%= form.text_field :physical_activity, class: 'form-control', title: 'Quais?' %>
        </div>
        <div class="form-group">
          <%= form.label :aerobic_activity %>
          <%= form.text_field :aerobic_activity, class: 'form-control', title: 'Frequencia?' %>
        </div>
        <div class="form-group">
          <%= form.label :other_activity %>
          <%= form.text_field :other_activity, class: 'form-control', title: 'Explique' %>
        </div>
      </div>
      <div class="col-sm-2">
        &nbsp;
      </div>
      <div class="actions col-12" style="width: 100%">
        <%= form.submit('Atualizar Histórico Social',{class: 'btn btn-primary'}) %>
      </div>
    </div>
  </div>
<% end %>

app/views/patients/create.js.erb
//$('#modal-window').on('hidden.bs.modal', function () {
//    location.reload();
//});
$("#modal-window").modal('toggle');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    //location.reload();
    $('#dttb-patients').DataTable().ajax.reload();
})

app/views/patients/destroy.js.erb
//Fecha o fundo do modal com detalhes do datatable
$(".dtr-modal").toggle(false)
//Fecha a div de detalhes do modal do datatable
$(".dtr-modal-display").toggle(false)

//Renderiza as mensagens
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    //atualiza datatable
    $('#dttb-patients').DataTable().ajax.reload();
})

app/views/patients/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal(_init()).animate({ scrollTop: 0 }, 'slow');

if ($("#patients_birth").val() == "" || $("#patients_birth").val() === undefined){
    bind_patient_birth()
}
else{
    setPatientAge($("#patients_birth").val());
}

app/views/patients/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="sectionform">

        <h1>Pacientes</h1>

        <table class="responsive table table-hover" id="dttb-patients" data-sort="true">
          <thead>
            <tr>
              <th data-data="patient_since">Patient since</th>
              <th data-data="protocol_and_name">Name</th>
              <th data-data="birth">Birth</th>
              <th data-data="age">Age</th>
              <th data-data="cpf">Cpf</th>
              <th data-data="gender">Gender</th>
              <th data-data="etnia">Etnia</th>
              <th data-data="civil_status">Civil status</th>
              <th data-data="occupation">Occupation</th>
              <th data-data="scholarity">Scholarity</th>
              <th data-data="zip">Zip</th>
              <th data-data="address">Address</th>
              <th data-data="city">City</th>
              <th data-data="uf">Uf</th>
              <th data-data="telephone">Telephone</th>
              <th data-data="mobile">Mobile</th>
              <th data-data="email">Email</th>
              <th data-data="indication_by">Indication by</th>
              <th data-data="health_plan">Health plan</th>
              <th data-data="plan_validation">Plan validation</th>
              <th data-data="plan_number">Plan number</th>
              <th data-data="created_at">Created at</th>
              <th data-data="updated_at">Updated at</th>
              <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
            </tr>
          </thead>
        </table>
        <br>
        <%= link_to 'Novo Paciente', new_patient_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal(_init()).animate({ scrollTop: 0 }, 'slow');
bind_patient_birth();

app/views/patients/update.js.erb
//$('#modal-window').on('hidden.bs.modal', function () {
//    location.reload();
//});

$(".dtr-modal").toggle(false)
$(".dtr-modal-display").toggle(false)
// fechamos o modal principal
$("#modal-window").modal('toggle');
$("#application-messages").html('<%= j render partial: 'layouts/messages' %>');
$(".alert").delay(2000).slideUp(200, function () {
    //location.reload();
    $('#dttb-appointments').DataTable().ajax.reload();
    $('#dttb-patients').DataTable().ajax.reload();
})