config/routes.rb
Rails.application.routes.draw do
  post '/d/new_and_associate' => 'diseases#new_and_associate_patient', as: :new_and_associate_patient, format: :js
  resources :diseases, path: "d", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_disease_code, on: :collection
    get ':patient_id/associate' => 'diseases#associate_patient', as: :associate_patient
    delete ':patient_id/delete' => 'diseases#delete_associate_patient', as: :delete_associate_patient
  end
  resources :consultations
  resources :exams
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, path: "u", path_names: { edit: "e", new: "novo" }
  resources :appointments, path: "consulta", path_names: { edit: "e", new: "novo" }
  resources :patients, path: "p", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_patient_all, on: :collection
  end

  get '/agenda' => 'protocol#protocol', as: :protocol #, format: false
  get '/pesquisar' => 'protocol#search', as: :search #, format: false
  get '/historico/*id' => 'protocol#historic', as: :historic #, format: false

  # config/routes.rb
  get "/pages/*id" => 'pages#show', as: :page, format: false

  # if routing the root path, update for your controller
  root to: 'pages#show', id: 'about'

  delete "/file/:id" => 'application#delete_file', as: :delete_file

  #root to: 'visitors#index'

end

app/controllers/protocol_controller.rb
class ProtocolController < ApplicationController
  before_action :admin_only, :only=> [:historic]

  def protocol
    @today = Time.now
  end

  def search
    @today = Time.now
  end

  def historic
    # recupera histórico do paciente
    @patient = Patient.find(params[:id])
    if @patient.protocol_number.blank?
      last_protocol_number = Patient.maximum(:protocol_number)
      @patient.protocol_number = last_protocol_number + 1
    end
  end
end

app/helpers/protocol_helper.rb
module ProtocolHelper
end

app/views/protocol/historic.html.erb
<div class="sectionform">
  <div class="row">
    <div class="col-sm-12">
      <h3>Histórico: <%= @patient.protocol_and_name.camelcase %></h3>
      <% if !@patient.last_appointment.blank? %>
        <h5>Última Consulta: <%= @patient.last_appointment %></h5>
      <% end %>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#profile" style="font-size: 1.2em; text-align: left">Dados Pessoais</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#consultations" style="font-size: 1.2em; text-align: left">Prontuário</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#exams" style="font-size: 1.2em; text-align: left">Exames</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#diseases" style="font-size: 1.2em; text-align: left">Problemas do paciente</a>
        </li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane show active" id="profile">
          <%= render 'patients/form', patient: @patient %>
        </div>
        <div class="tab-pane" id="consultations">
          <%= render 'patients/consultations', patient: @patient %>
        </div>
        <div class="tab-pane" id="exams">
          <%= render 'patients/exams', patient: @patient %>
        </div>
        <div class="tab-pane" id="diseases">
          <%= render 'patients/diseases', patient: @patient %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="modal-patient" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog mw-100 w-75" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/protocol/protocol.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="sectionform">
      <h3>Agenda</h3>
      <div class="form-group row">
        <div class="input-group date-picker col-sm-6" id="datepicker-date-appointments" data-target-input="nearest">
          <%= text_field_tag :appointements_date, @today.strftime('%d/%m/%Y'), class:'form-control datetimepicker-input', data:{target:'#datepicker-date-appointments'} %>
          <div class="input-group-append" data-target="#datepicker-date-appointments" data-toggle="datetimepicker">
            <div class="input-group-text"><%= icon('far', 'calendar-alt') %></div>
          </div>
        </div>
        <div class="col-sm-6">
          <%= link_to 'Marcar Novo Horário', new_appointment_path,  {:remote => true, data:{toggle: "modal", target: '#modal-window'}, class:"btn btn-primary"} %>
        </div>
      </div>
      <table class="responsive table table-hover" id="dttb-appointments" data-sort="true" data-source="<%= appointments_path(appointments_date: Time.now().strftime('%d/%m/%Y'), format: :json) %>">
        <thead>
        <tr>
          <!--<th data-data="empty_collumn"></th>-->
          <th data-data="appointment_date" style="max-width: 70px">Horário</th>
          <th data-data="name" style="min-width: 220px">Paciente</th>
          <th data-data="appointment_kind" style="max-width: 70px">Tipo</th>
          <th data-data="status" style="max-width: 70px ">Status</th>
          <th data-data="last_appointment" style="max-width: 70px">Última Consulta</th>
          <th data-data="health_insurance" style="max-width: 70px">Convênio</th>
          <th data-data="mobile" style="max-width: 90px">Telefone</th>
          <th data-data="url" data-orderable="false" data-searchable="false" class="skip-export">Ações</th>
        </tr>
        </thead>
      </table>
      <br>
      <%#= link_to 'Marcar Horário', new_appointment_path,  {:local => true, class:"btn btn-primary"} %>
      <%= link_to 'Marcar Novo Horário', new_appointment_path,  {:remote => true, data:{toggle: "modal", target: '#modal-window'}, class:"btn btn-primary"} %>
    </div>
  </div>
</div>
<%#= link_to 'TESTE MODAL', new_patient_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-appointment', class: 'btn btn-primary btn-lg'}  %>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog mw-100 w-75" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/protocol/search.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="sectionform">
      <h3>Pacientes</h3>
      <table class="responsive table table-hover " id="dttb-patients" data-sort="true">
        <thead>
        <tr>
          <th data-data="protocol_number"  style="max-width: 55px">Protocolo</th>
          <th data-data="name" class="all" style="min-width: 150px">Nome</th>
          <th data-data="birth" class="">Nascimento</th>
          <th data-data="age" class="" style="max-width: 31px">Idade</th>
          <th data-data="cpf" class="no-sort" style="min-width: 100px">CPF</th>
          <th data-data="last_appointment" class="no-sort" style="min-width: 90px">Última Consulta</th>
          <th data-data="gender" class="none no-sort">Gênero</th>
          <th data-data="patient_since" class="none no-sort">Paciente Desde</th>
          <th data-data="etnia" class="none no-sort">Etnia</th>
          <th data-data="civil_status" class="none no-sort">Estado Civil</th>
          <th data-data="occupation" class="none no-sort">Profissão</th>
          <th data-data="scholarity" class="none no-sort">Escolaridade</th>
          <th data-data="zip" class="none no-sort">CEP</th>
          <th data-data="address" class="none no-sort">Endereço</th>
          <th data-data="city" class="none no-sort">Cidade</th>
          <th data-data="district" class="none no-sort">Bairro</th>
          <th data-data="uf" class="none no-sort">UF</th>
          <th data-data="telephone" class="no-sort" style="min-width: 100px">Telefone</th>
          <th data-data="mobile" class="no-sort" style="min-width: 100px">Celular</th>
          <th data-data="email" class="no-sort">Email</th>
          <th data-data="indication_by" class="none no-sort">Indicado por</th>
          <th data-data="health_insurance" class="none no-sort">Convênio</th>
          <th data-data="health_plan" class="none no-sort">Nome do Plano</th>
          <th data-data="plan_validation" class="none no-sort">Valido até</th>
          <th data-data="plan_number" class="none no-sort">Número Carteirinha</th>
          <th data-data="url" data-orderable="false" data-searchable="false" class="none skip-export no-sort" width="100px">Ações</th>
        </tr>
        </thead>
      </table>
      <br>
      <%= link_to 'Novo Paciente', new_patient_path,  {:remote => true, data:{toggle:  "modal", target: '#modal-window'}, class:"btn btn-primary"} %>
    </div>
  </div>
</div>
<%#= link_to 'TESTE MODAL', new_patient_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-appointment', class: 'btn btn-primary btn-lg'}  %>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog mw-100 w-75" role="document">
    <div class="modal-content"></div>
  </div>
</div>