config/routes.rb
Rails.application.routes.draw do
  post '/d/new_and_associate' => 'diseases#new_and_associate_patient', as: :new_and_associate_patient, format: :js
  resources :diseases, path: "d", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_disease_code, on: :collection
    get ':patient_id/associate' => 'diseases#associate_patient', as: :associate_patient
    delete ':patient_id/delete' => 'diseases#delete_associate_patient', as: :delete_associate_patient
  end
  resources :consultations
  resources :exams
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, path: "u", path_names: { edit: "e", new: "novo" }
  resources :appointments, path: "consulta", path_names: { edit: "e", new: "novo" }
  resources :patients, path: "p", path_names: { edit: "e", new: "novo" } do
    get :autocomplete_patient_all, on: :collection
  end

  get '/agenda' => 'protocol#protocol', as: :protocol #, format: false
  get '/pesquisar' => 'protocol#search', as: :search #, format: false
  get '/historico/*id' => 'protocol#historic', as: :historic #, format: false

  # config/routes.rb
  get "/pages/*id" => 'pages#show', as: :page, format: false

  # if routing the root path, update for your controller
  root to: 'pages#show', id: 'about'

  delete "/file/:id" => 'application#delete_file', as: :delete_file

  #root to: 'visitors#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Agenda', protocol_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Pesquisa', search_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Minha Conta', edit_user_registration_path, class: 'nav-link' %></li>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Usuários', users_path, class: 'nav-link' %></li>
  <% end %>
  <li class='nav-item'><%= link_to 'Sair', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sobre', page_path('about'), class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Cadastre-se', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="/"><%= image_tag asset_url('bubu_doctor_logo.png'), width: '100%' %></a>
  <!--<a class="navbar-brand" href="#"><%#= image_tag asset_url('BubuDoctorFullFinal3.png'), width: '100%' %></a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse" style="font-size: 2em;">
    <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
    <% if user_signed_in? %>
      <div style="margin-left:auto; margin-right:0;">
        <small><%= current_user.email %></small>
      </div>
    <% end %>

    <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
    </ul>
    -->
    <!--
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bubudoctor" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bubudoctor" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <div id="application-messages">
         <%= render 'layouts/messages' %>
       </div>
        <div class="container-fluid">
          <%= yield %>
        </div>
    </main>
  </body>
</html>